username: 'YuliyaSha2023'
password: '9c41b200e5'
url: 'https://test-stand.gb.ru/gateway/login'
url_posts: 'https://test-stand.gb.ru/api/posts'
title: 'Собака'
description: 'Плацентарное млекопитающее отряда хищных семейства псовых'
content: 'Соба́ка — домашнее животное, одно из наиболее популярных животных-компаньонов. Домашняя собака была описана 
как самостоятельный биологический вид Canis familiaris Линнеем в 1758 году; в настоящее время данное научное название 
признаётся организациями, такими как Американское общество маммалогов.'